'use strict';

/* Seed content the database is initialised with on first run. Mirrors the
   bundled front-end seed so the static landing and the API agree. No em/en
   dashes. Non-ASCII is escaped so the file is encoding-safe. */

const books = [
  { id: 'seed-1', title: 'The Lantern Orchard', author: 'M. Ashgrove', rating: '4.8', price: '$24', tint: 'linear-gradient(160deg,#5a3a28,#2e1d13)', lang: '', roast: 'Med', notes: 'pear, woodsmoke, long finish', genre: 'Fiction', mood: ['cozy', 'thoughtful'], pace: 'slow', ending: 'hopeful', summary: 'On the night the orchard lights its thousand lanterns, a grieving daughter returns to the family grove and learns that some debts are paid in fruit and in forgiveness.', pages: 328, year: 2021, reviews: 1284, custom: false },
  { id: 'seed-2', title: 'Sugar & Smoke', author: 'D. Fenwick', rating: '4.6', price: '$19', tint: 'linear-gradient(160deg,#4a3526,#251a12)', lang: '', roast: 'Dark', notes: 'cocoa, char, bittersweet', genre: 'Mystery', mood: ['heart-racing'], pace: 'fast', ending: 'bittersweet', summary: 'A pastry chef with a ruined reputation is pulled into the death of a rival baker, and every clue tastes faintly of caramel and of revenge.', pages: 296, year: 2023, reviews: 842, custom: false },
  { id: 'seed-3', title: 'A Year of Small Rains', author: 'I. Voss', rating: '4.9', price: '$22', tint: 'linear-gradient(160deg,#7a4332,#3a201a)', lang: '', roast: 'Light', notes: 'rain, bergamot, clean', genre: 'Nonfiction', mood: ['thoughtful', 'cozy'], pace: 'slow', ending: 'hopeful', summary: 'Twelve essays, one for each month, on weather, patience, and the quiet art of paying close attention to an ordinary life.', pages: 244, year: 2020, reviews: 1976, custom: false },
  { id: 'seed-4', title: 'The Quiet Between Stars', author: 'N. Calder', rating: '4.7', price: '$26', tint: 'linear-gradient(160deg,#5e3550,#301a2c)', lang: '', roast: 'Med', notes: 'plum, dusk, slow burn', genre: 'Fantasy', mood: ['melancholy', 'thoughtful'], pace: 'medium', ending: 'open', summary: 'Two cartographers map a dying constellation and discover that the silence between the stars has been keeping a secret for a very long time.', pages: 412, year: 2022, reviews: 1530, custom: false },
  { id: 'seed-5', title: 'Salt House', author: 'E. Marsh', rating: '4.5', price: '$18', tint: 'linear-gradient(160deg,#6e4348,#352025)', lang: '', roast: 'Med', notes: 'brine, almond, melancholy', genre: 'Fiction', mood: ['melancholy'], pace: 'slow', ending: 'bittersweet', summary: 'A family returns to a crumbling house by the sea to settle an estate, and the tide keeps returning the things they meant to leave buried.', pages: 268, year: 2019, reviews: 654, custom: false },
  { id: 'seed-6', title: "Le Jardin d'Hiver", author: 'C. Aubry', rating: '4.8', price: '$27', tint: 'linear-gradient(160deg,#6a4a2e,#33241a)', lang: 'Fran\u00E7ais', roast: 'Light', notes: 'honey, frost, tender', genre: 'Romance', mood: ['cozy', 'hopeful'], pace: 'medium', ending: 'hopeful', summary: 'In a frost-bound winter garden, two strangers agree to meet once a week until spring, and neither one expects the thaw to reach quite so far.', pages: 352, year: 2021, reviews: 1120, custom: false },
  { id: 'seed-7', title: 'Tea for the Wandering', author: 'R. Pellow', rating: '4.6', price: '$21', tint: 'linear-gradient(160deg,#5a4a30,#2e2618)', lang: '', roast: 'Med', notes: 'cardamom, road dust, warm', genre: 'Fantasy', mood: ['whimsical', 'cozy'], pace: 'medium', ending: 'open', summary: 'A traveling tea seller crosses seven kingdoms with a kettle that never empties and a map that keeps redrawing itself toward home.', pages: 380, year: 2023, reviews: 990, custom: false },
  { id: 'seed-8', title: '\u0623\u0648\u0631\u0627\u0642 \u0627\u0644\u062E\u0631\u064A\u0641', author: 'L. Haddad', rating: '4.9', price: '$23', tint: 'linear-gradient(160deg,#5a3340,#33212a)', lang: '\u0627\u0644\u0639\u0631\u0628\u064A\u0629', roast: 'Dark', notes: 'fig, amber, lingering', genre: 'Poetry', mood: ['melancholy', 'hopeful'], pace: 'slow', ending: 'bittersweet', summary: 'A slim collection of autumn poems about memory, exile, and the amber light that falls only in the last weeks before the cold.', pages: 176, year: 2018, reviews: 1340, custom: false },
];

const events = [
  { id: '0', month: 'Feb', day: '14', icon: 'heart', type: 'Sweetheart night', title: 'Blind-date-with-a-book & cocoa social', time: 'Fri \u00B7 7:00pm', place: 'the back room', spots: 'Limited to 24 seats',
    desc: ['Our busiest night of the season. The back room fills with candles, the cocoa pot never stops, and every guest leaves with a book wrapped in plain paper and three clues.', 'Come alone or drag a friend. Halfway through the night we read the clues aloud and let the room guess. Nobody guesses correctly. That has never once stopped anybody.'] },
  { id: '1', month: 'Feb', day: '18', icon: 'rose', type: 'Poetry night', title: 'Candlelit verse & cocoa, open mic', time: 'Tue \u00B7 8:00pm', place: 'the loft', spots: 'Open mic, drop-in',
    desc: ['Bring a poem, yours or someone else\u2019s, or bring only your ears. The loft seats about thirty if everyone is friendly, and on poetry night everyone is friendly.', 'The list opens at 7:45 and fills fast. Five minutes a reader, one cup of cocoa per poem, and a strictly enforced policy of generous applause.'] },
  { id: '2', month: 'Feb', day: '22', icon: 'balloon', type: 'Storytime', title: 'Saturday morning tales for tiny readers', time: 'Sat \u00B7 10:30am', place: 'the kids nook', spots: 'Best for ages 3 to 7',
    desc: ['Half an hour of picture books, silly voices, and one song we are all slightly too old to be singing. Caregivers get a quiet cup while the little ones sit on the rug.', 'No need to reserve, but a heads-up helps us pull enough cushions. Latecomers are always welcome at the back of the rug.'] },
  { id: '3', month: 'Feb', day: '25', icon: 'cup', type: 'Book club', title: 'Sugar & Smoke: pastries & pour-overs', time: 'Tue \u00B7 6:30pm', place: 'the counter', spots: 'Read along first',
    desc: ['This month we are arguing about Sugar & Smoke over pour-overs and whatever the kitchen pulled out of the oven that afternoon. Strong opinions encouraged, spoilers fully expected.', 'You do not have to finish the book to come, but you will enjoy yourself more if the ending is fresh. We meet at the long counter near the window.'] },
];

const articles = [
  { id: '0', cat: 'Staff picks', date: 'Feb 12', read: '4 min read', icon: 'cup', tint: 'linear-gradient(160deg,#5a4a30,#2e2618)', title: 'Six books that pair with a flat white', excerpt: 'Crisp prose, woodsmoke moods, and at least one with a recipe for cardamom coffee tucked in the back.',
    body: ['A flat white is a quiet drink. No foam to speak of, no theatrics, just espresso and steamed milk meeting in the middle. The books that pair with it are the same: unhurried, warm, and a little stronger than they look.', 'We started this list on a slow Tuesday when the rain would not let up and the counter was empty. By the second cup we had argued our way down to six titles, and by the third we had stopped pretending the order mattered.', 'The first is the kind of novel you read with your shoulders down. Long sentences, a small town, a narrator who notices the weather. The second is sharper, all dialogue and bad decisions, the literary equivalent of the second shot you did not plan to order.', 'Halfway through the shelf there is a slim book of essays about kitchens, and yes, there is a recipe for cardamom coffee folded into the last chapter. We have made it. It is very good, and it has no business being in a book about grief, which is exactly why it works.', 'If you only take one home, take the one with the orchard on the cover. Read it slowly. Let the milk go a little cool. Some stories are better at the temperature of a forgotten cup.'] },
  { id: '1', cat: 'Behind the counter', date: 'Feb 06', read: '3 min read', icon: 'rose', tint: 'linear-gradient(160deg,#5a3340,#33212a)', title: 'How we wrap a blind date', excerpt: 'The art of three clues and zero spoilers. A peek into the most secretive corner of the shop.',
    body: ['Every blind date with a book starts the same way: a keeper stands at the back table, holds a book they love, and tries to describe it without giving anything away. This is harder than it sounds, and it is the best part of the job.', 'The rule is three clues and zero spoilers. A mood, a texture, and one small promise. "Slow burn, salt air, ends softer than it begins." That is the whole pitch. No title, no author, no cover. Just enough to make you curious and not enough to make you sure.', 'We wrap them in plain paper so the weight and shape give nothing away either. A thin book of poems and a doorstop of a novel should feel like a gamble right up until you tear the corner.', 'People ask if we are ever tempted to match the book to the person. We are, constantly, and we try not to. The whole point of a blind date is that it is not optimised. Sometimes the best book you read all year is the one an algorithm would never have handed you.'] },
  { id: '2', cat: 'Reading life', date: 'Jan 29', read: '5 min read', icon: 'moon', tint: 'linear-gradient(160deg,#5e3550,#301a2c)', title: 'In praise of the slow re-read', excerpt: 'Why the second visit to a story is often the kinder one, and the books we return to each year.',
    body: ['There is a particular kind of reader who never opens the same book twice, and we understand them, and we are not them. Some books are houses you move into. You learn where the light falls. You come back.', 'The first read is for the plot. You are turning pages to find out, and that hunger is its own pleasure. The second read is for everything the hunger made you skip: the way a minor character is quietly breaking, the joke planted two hundred pages before its punchline.', 'A re-read is also a way of measuring yourself. The book has not changed since last winter, but you have, and the parts that move you now are not the parts that moved you then. The same paragraph that felt sentimental at twenty can level you at thirty-five.', 'We keep a short shelf behind the counter of books we return to every year. None of them are the ones we would call the best books we have ever read. They are just the ones that feel like coming home, and that turns out to be a different and more useful thing.', 'So if you finished something this month and felt that small ache of leaving, consider not leaving. Go back to page one. The story will be the same. You will not be, and that is the entire point.'] },
];

export default { books, events, articles };
